### ISSUE TITLE
Support for Matlab syntax

### ISSUE THREAD

**Issue by AllanLRH** [SublimeText/NaturalDocs#12]
Matlab used `%` to denote comments – would be nice if this awesome plugin would support Matlab (and other weird languages, maybe by using comment-templates?) comments as well :)

Maybe something like (`%%` have a special meaning in Matlab code)

```matlab
%-%-%-%-%-%-%-%-%-%-%-%-%-%-%-%-%
%   A nicely decorated comment  %
%-%-%-%-%-%-%-%-%-%-%-%-%-%-%-%-%
```

**Comment by AllanLRH** [comment]
Finally got around to do this. I've made pull requests for the master and python3 branches, because I unfortunately couldn't figure out how to include both in the same pull request… is it even possible? :confused:

**Comment by njlg** [comment]
Thanks for looking in to this. I don't think there is a way to make a PR to two different branches... in other words: You did it right!
